setwd("D:/datascience/4")
datafull <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data <- subset(datafull, Date %in% c("1/2/2007","2/2/2007"))
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
datetime <- paste(as.Date(data$Date), data$Time)
data$Datetime <- as.POSIXct(datetime)
with(data, plot(Global_active_power~Datetime,type="l",xlab="",ylab="Global Active Power (kilowatts)"))
dev.copy(png,"plot2.png",height=480, width=480)
dev.off()